### ISSUE TITLE
Login Error 

### ISSUE THREAD

**Issue by wesjthomas** [sukebenet/sukebezone-tracker#19]
Hi,

I am trying to log in to my account but keep getting the error:

'getaddrinfo ENOTFOUND mariadb'

Please advise. Thanks.

**Comment by hlarsonn** [comment]
I have the same issue. 
I contacted hCaptcha about the issue and after a few emails back and forth I got this reply:

"This is not an hCaptcha related error, so there is nothing we can do about it.
Please, in order to solve it, contact the website owner".

**Comment by kolessios** [comment]
Thank you for reporting the problem, it has been fixed.
